//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBased {
    
    
    [ModellMeister.Runtime.RootModelAttribute()]
    public partial class _ : ModellMeister.Runtime.IModelType {
        
        private ModelBased.RandomType _Random;
        
        private ModelBased.SquareType _Square;
        
        private ModelBased.ToConsoleType _ToConsole;
        
        public ModelBased.RandomType Random {
            get {
                return this._Random;
            }
            set {
                this._Random = value;
            }
        }
        
        public ModelBased.SquareType Square {
            get {
                return this._Square;
            }
            set {
                this._Square = value;
            }
        }
        
        public ModelBased.ToConsoleType ToConsole {
            get {
                return this._ToConsole;
            }
            set {
                this._ToConsole = value;
            }
        }
        
        public void Init() {
            this._Random = new ModelBased.RandomType();
            this._Random.Init();
            this._Square = new ModelBased.SquareType();
            this._Square.Init();
            this._ToConsole = new ModelBased.ToConsoleType();
            this._ToConsole.Init();
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this._Random.Execute(info);
            this.Square.Input = this.Random.Output;
            this._Square.Execute(info);
            this.ToConsole.Input = this.Square.Output;
            this._ToConsole.Execute(info);
        }
    }
    
    public partial class RandomType : ModellMeister.Runtime.IModelType {
        
        private double _Output;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Output {
            get {
                return this._Output;
            }
            set {
                this._Output = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class SquareType : ModellMeister.Runtime.IModelType {
        
        private double _Input;
        
        private double _Output;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input {
            get {
                return this._Input;
            }
            set {
                this._Input = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Output {
            get {
                return this._Output;
            }
            set {
                this._Output = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class ToConsoleType : ModellMeister.Runtime.IModelType {
        
        private double _Input;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input {
            get {
                return this._Input;
            }
            set {
                this._Input = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
}
