//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBased {
    
    
    [ModellMeister.Runtime.RootModelAttribute()]
    public partial class _ : ModellMeister.Runtime.IModelType {
        
        private ModelBased.Constant _Source1;
        
        private ModelBased.Constant _Source2;
        
        private ModelBased.Constant _Source3;
        
        private ModelBased.ThreeAdder _Summer;
        
        private ModelBased.CSVWriter _Writer;
        
        public ModelBased.Constant Source1 {
            get {
                return this._Source1;
            }
            set {
                this._Source1 = value;
            }
        }
        
        public ModelBased.Constant Source2 {
            get {
                return this._Source2;
            }
            set {
                this._Source2 = value;
            }
        }
        
        public ModelBased.Constant Source3 {
            get {
                return this._Source3;
            }
            set {
                this._Source3 = value;
            }
        }
        
        public ModelBased.ThreeAdder Summer {
            get {
                return this._Summer;
            }
            set {
                this._Summer = value;
            }
        }
        
        public ModelBased.CSVWriter Writer {
            get {
                return this._Writer;
            }
            set {
                this._Writer = value;
            }
        }
        
        public void Init() {
            this._Source1 = new ModelBased.Constant();
            this._Source1.Init();
            this._Source2 = new ModelBased.Constant();
            this._Source2.Init();
            this._Source3 = new ModelBased.Constant();
            this._Source3.Init();
            this._Summer = new ModelBased.ThreeAdder();
            this._Summer.Init();
            this._Writer = new ModelBased.CSVWriter();
            this._Writer.Init();
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this._Source1.Execute(info);
            this._Source2.Execute(info);
            this._Source3.Execute(info);
            this.Summer.OuterSummand1 = this.Source1.Output;
            this.Summer.OuterSummand2 = this.Source2.Output;
            this.Summer.OuterSummand3 = this.Source3.Output;
            this._Summer.Execute(info);
            this.Writer.Input = this.Summer.OuterSum;
            this._Writer.Execute(info);
        }
    }
    
    public partial class Sine : ModellMeister.Runtime.IModelType {
        
        private double _Output;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Output {
            get {
                return this._Output;
            }
            set {
                this._Output = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class Constant : ModellMeister.Runtime.IModelType {
        
        private double _Output;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Output {
            get {
                return this._Output;
            }
            set {
                this._Output = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class Adder : ModellMeister.Runtime.IModelType {
        
        private double _Summand1;
        
        private double _Summand2;
        
        private double _Sum;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Summand1 {
            get {
                return this._Summand1;
            }
            set {
                this._Summand1 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Summand2 {
            get {
                return this._Summand2;
            }
            set {
                this._Summand2 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Sum {
            get {
                return this._Sum;
            }
            set {
                this._Sum = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class CSVWriter : ModellMeister.Runtime.IModelType {
        
        private double _Input;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input {
            get {
                return this._Input;
            }
            set {
                this._Input = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class ThreeAdder : ModellMeister.Runtime.IModelType {
        
        private double _OuterSummand1;
        
        private double _OuterSummand2;
        
        private double _OuterSummand3;
        
        private double _OuterSum;
        
        private ModelBased.Adder _Summer1;
        
        private ModelBased.Adder _Summer2;
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double OuterSummand1 {
            get {
                return this._OuterSummand1;
            }
            set {
                this._OuterSummand1 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double OuterSummand2 {
            get {
                return this._OuterSummand2;
            }
            set {
                this._OuterSummand2 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double OuterSummand3 {
            get {
                return this._OuterSummand3;
            }
            set {
                this._OuterSummand3 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double OuterSum {
            get {
                return this._OuterSum;
            }
            set {
                this._OuterSum = value;
            }
        }
        
        public ModelBased.Adder Summer1 {
            get {
                return this._Summer1;
            }
            set {
                this._Summer1 = value;
            }
        }
        
        public ModelBased.Adder Summer2 {
            get {
                return this._Summer2;
            }
            set {
                this._Summer2 = value;
            }
        }
        
        public void Init() {
            this._Summer1 = new ModelBased.Adder();
            this._Summer1.Init();
            this._Summer2 = new ModelBased.Adder();
            this._Summer2.Init();
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.Summer1.Summand1 = this.OuterSummand1;
            this.Summer1.Summand2 = this.OuterSummand2;
            this._Summer1.Execute(info);
            this.Summer2.Summand1 = this.Summer1.Sum;
            this.Summer2.Summand2 = this.OuterSummand3;
            this._Summer2.Execute(info);
            this.OuterSum = this.Summer2.Sum;
        }
    }
}
