//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34209
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBased {
    
    
    [ModellMeister.Runtime.RootModelAttribute()]
    public partial class _ : ModellMeister.Runtime.IModelType {
        
        private ModelBased.Sine _Source1;
        
        private ModelBased.Constant _Source2;
        
        private ModelBased.Adder _Summer;
        
        private ModelBased.CSVWriter _Writer;
        
        public ModelBased.Sine Source1 {
            get {
                return this._Source1;
            }
            set {
                this._Source1 = value;
            }
        }
        
        public ModelBased.Constant Source2 {
            get {
                return this._Source2;
            }
            set {
                this._Source2 = value;
            }
        }
        
        public ModelBased.Adder Summer {
            get {
                return this._Summer;
            }
            set {
                this._Summer = value;
            }
        }
        
        public ModelBased.CSVWriter Writer {
            get {
                return this._Writer;
            }
            set {
                this._Writer = value;
            }
        }
        
        public void Init() {
            this._Source1 = new ModelBased.Sine();
            this._Source1.Init();
            this._Source2 = new ModelBased.Constant();
            this._Source2.Init();
            this._Summer = new ModelBased.Adder();
            this._Summer.Init();
            this._Writer = new ModelBased.CSVWriter();
            this._Writer.Init();
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this._Source1.Execute(info);
            this._Source2.Execute(info);
            this.Summer.Summand1 = this.Source1.Output;
            this.Summer.Summand2 = this.Source2.Output;
            this._Summer.Execute(info);
            this.Writer.Input = this.Summer.Sum;
            this._Writer.Execute(info);
        }
    }
    
    public partial class Sine : ModellMeister.Runtime.IModelType {
        
        private double _Output;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Output {
            get {
                return this._Output;
            }
            set {
                this._Output = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class Constant : ModellMeister.Runtime.IModelType {
        
        private double _Output;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Output {
            get {
                return this._Output;
            }
            set {
                this._Output = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class Adder : ModellMeister.Runtime.IModelType {
        
        private double _Summand1;
        
        private double _Summand2;
        
        private double _Sum;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Summand1 {
            get {
                return this._Summand1;
            }
            set {
                this._Summand1 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Summand2 {
            get {
                return this._Summand2;
            }
            set {
                this._Summand2 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Sum {
            get {
                return this._Sum;
            }
            set {
                this._Sum = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class CSVWriter : ModellMeister.Runtime.IModelType {
        
        private double _Input;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input {
            get {
                return this._Input;
            }
            set {
                this._Input = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
}
