//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBased
{

    public partial class Sine
    {

        private double time = 0.0;

        partial void DoExecute()
        {
            time += 0.1;
            this.Output = System.Math.Sin(time);
        }
    }

    public partial class Constant
    {

        partial void DoExecute()
        {
            this.Output = 1;
        }
    }

    public partial class Adder
    {

        partial void DoExecute()
        {
            this.Sum = this.Summand1 + this.Summand2;
        }
    }

    public partial class CSVWriter
    {
        partial void DoExecute()
        {
            System.Console.WriteLine(this.Input);
        }
    }
}
