//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBased
{
    
    
    public partial class _
    {
    }
    
    public partial class Summer
    {
        
        private double _Summand1;
        
        private double _Summand2;
        
        private double _Sum;
        
        public virtual double Summand1
        {
            get
            {
                return this._Summand1;
            }
            set
            {
                this._Summand1 = value;
            }
        }
        
        public virtual double Summand2
        {
            get
            {
                return this._Summand2;
            }
            set
            {
                this._Summand2 = value;
            }
        }
        
        public virtual double Sum
        {
            get
            {
                return this._Sum;
            }
            set
            {
                this._Sum = value;
            }
        }
    }
}
