//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBased {
    
    
    [ModellMeister.Runtime.RootModelAttribute()]
    public partial class _ : ModellMeister.Runtime.IModelType {
        
        private Adder _FirstSummer;
        
        private Adder _SecondSummer;
        
        public Adder FirstSummer {
            get {
                return this._FirstSummer;
            }
            set {
                this._FirstSummer = value;
            }
        }
        
        public Adder SecondSummer {
            get {
                return this._SecondSummer;
            }
            set {
                this._SecondSummer = value;
            }
        }
        
        public void Init() {
            this._FirstSummer = new Adder();
            this._FirstSummer.Init();
            this._SecondSummer = new Adder();
            this._SecondSummer.Init();
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this._FirstSummer.Execute(info);
            this.SecondSummer.Summand1 = this.FirstSummer.Sum;
            this._SecondSummer.Execute(info);
        }
    }
    
    public partial class Adder : ModellMeister.Runtime.IModelType {
        
        private double _Summand1;
        
        private double _Summand2;
        
        private double _Sum;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        public double Summand1 {
            get {
                return this._Summand1;
            }
            set {
                this._Summand1 = value;
            }
        }
        
        public double Summand2 {
            get {
                return this._Summand2;
            }
            set {
                this._Summand2 = value;
            }
        }
        
        public double Sum {
            get {
                return this._Sum;
            }
            set {
                this._Sum = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
}
