//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelBased {
    
    
    public class Summer {
        
        private double Summand1 {
        }
        
        private double Summand2 {
        }
        
        private double Sum {
        }
    }
    
    public class Multiplier {
        
        private double Factor1 {
        }
        
        private double Factor2 {
        }
        
        private double Product {
        }
    }
}
