using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ModellMeister.Model
{
    /// <summary>
    /// Defines the base class for the types. 
    /// Possible inherits are: ModelNativeType and ModelCompositeType
    /// </summary>
    public abstract class ModelType : EntityWithPorts
    {
        /// <summary>
        /// Stores the namespace of the modeltype. 
        /// </summary>
        private string nameSpace = string.Empty;

        /// <summary>
        /// Gets or sets a value indicating whether the
        /// type was loaded from a library, so it does not need to get recreated
        /// </summary>
        public bool IsInLibrary
        {
            get;
            set;
        }

        /// <summary>
        /// Gets or sets the namespace
        /// </summary>
        public string NameSpace
        {
            get { return this.nameSpace; }
            set { this.nameSpace = value; }
        }

        /// <summary>
        /// Gets or sets a value indicating whether the type was autogenerated
        /// </summary>
        public bool IsAutoGenerated
        {
            get;
            set;
        }
    }
}
