using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ModellMeister.Model
{
    /// <summary>
    /// Defines the base class for the types. 
    /// Possible inherits are: ModelNativeType and ModelCompositeType
    /// </summary>
    public abstract class ModelType : EntityWithPorts
    {
        /// <summary>
        /// Gets or sets a value indicating whether the type was autogenerated
        /// </summary>
        public bool IsAutoGenerated
        {
            get;
            set;
        }
    }
}
