//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModellMeister.Library.Comparison {
    
    
    [ModellMeister.Runtime.RootModelAttribute()]
    public partial class _ : ModellMeister.Runtime.IModelType {
        
        public void Init() {
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
        }
    }
    
    public partial class Equal : ModellMeister.Runtime.IModelType {
        
        private double _Input1;
        
        private double _Input2;
        
        private bool _Result;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input1 {
            get {
                return this._Input1;
            }
            set {
                this._Input1 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input2 {
            get {
                return this._Input2;
            }
            set {
                this._Input2 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public bool Result {
            get {
                return this._Result;
            }
            set {
                this._Result = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class NotEqual : ModellMeister.Runtime.IModelType {
        
        private double _Input1;
        
        private double _Input2;
        
        private bool _Result;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input1 {
            get {
                return this._Input1;
            }
            set {
                this._Input1 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input2 {
            get {
                return this._Input2;
            }
            set {
                this._Input2 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public bool Result {
            get {
                return this._Result;
            }
            set {
                this._Result = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class GreaterThan : ModellMeister.Runtime.IModelType {
        
        private double _Input1;
        
        private double _Input2;
        
        private bool _Result;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input1 {
            get {
                return this._Input1;
            }
            set {
                this._Input1 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input2 {
            get {
                return this._Input2;
            }
            set {
                this._Input2 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public bool Result {
            get {
                return this._Result;
            }
            set {
                this._Result = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class SmallerThan : ModellMeister.Runtime.IModelType {
        
        private double _Input1;
        
        private double _Input2;
        
        private bool _Result;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input1 {
            get {
                return this._Input1;
            }
            set {
                this._Input1 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input2 {
            get {
                return this._Input2;
            }
            set {
                this._Input2 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public bool Result {
            get {
                return this._Result;
            }
            set {
                this._Result = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class GreaterOrEqualThan : ModellMeister.Runtime.IModelType {
        
        private double _Input1;
        
        private double _Input2;
        
        private bool _Result;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input1 {
            get {
                return this._Input1;
            }
            set {
                this._Input1 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input2 {
            get {
                return this._Input2;
            }
            set {
                this._Input2 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public bool Result {
            get {
                return this._Result;
            }
            set {
                this._Result = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
    
    public partial class SmallerOrEqualThan : ModellMeister.Runtime.IModelType {
        
        private double _Input1;
        
        private double _Input2;
        
        private bool _Result;
        
        partial void DoInit();
        
        partial void DoExecute(ModellMeister.Runtime.StepInfo info);
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input1 {
            get {
                return this._Input1;
            }
            set {
                this._Input1 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public double Input2 {
            get {
                return this._Input2;
            }
            set {
                this._Input2 = value;
            }
        }
        
        [ModellMeister.Runtime.Port(ModellMeister.Runtime.PortType.Input)]
        public bool Result {
            get {
                return this._Result;
            }
            set {
                this._Result = value;
            }
        }
        
        public void Execute(ModellMeister.Runtime.StepInfo info) {
            this.DoExecute(info);
        }
        
        public void Init() {
            this.DoInit();
        }
    }
}
